version: '3.7'
services:
  adguard:
    image: adguard/adguardhome
    ports:
     - 53:53/tcp
     - 53:53/udp
     - 67:67/udp
     - 68:68/tcp
     - 68:68/udp
     #- 80:80
     #- 443:443
     - 853:853/tcp
     - 853:853/udp
     - 3000:3000
    volumes:
     - /volumes/adguard/work:/opt/adguardhome/work
     - /volumes/adguard/config:/opt/adguardhome/conf
    networks:
     - dmz
    restart: unless-stopped
    labels:
     - traefik.enable=true
     - traefik.docker.network=dmz
     - traefik.http.routers.adguard.rule=Host("adguard.escasapool.com")
     - traefik.http.routers.adguard.entrypoints=http
     - traefik.http.services.adguard.loadbalancer.server.port=3000
networks:
  dmz:
    external: true
