docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 80:80/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp -d adguard/adguardhome

version: "3.7"
  adguard:
    image: adguard/adguardhome
    port:
     - 53:53
     - 67:67
     - 68:68
     #- 80:80
     #- 443:443
     - 853:853
     - 3000:3000
    volumes:
     - /volumes/adguard/work:/opt/adguardhome/work
     - /volumes/adguard/config:/opt/adguardhome/conf
    network:
     - dmz
    restart: unless-stopped
     
     
networks:
  dmz:
    external: true
