version: '3.7'
  adguard:
    image: adguard/adguardhome
    port:
     - 53:53
     - 67:67
     - 68:68
     #- 80:80
     #- 443:443
     - 853:853
     - 3000:3000
    volumes:
     - /volumes/adguard/work:/opt/adguardhome/work
     - /volumes/adguard/config:/opt/adguardhome/conf
    network:
     - dmz
    restart: unless-stopped
     
     
networks:
  dmz:
    external: true
